name: Update Docs

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: xu-cheng/latex-action@v2
      with:
        working_directory: docs
        root_file: primer.tex
        compiler: pdflatex

    - uses: actions/upload-artifact@v2
      with:
        name: primer-notes
        path: docs/primer.pdf
      
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        # Arguments for the git add command
        add: docs/primer.pdf
        # The name of the user that will be displayed as the author of the commit
        author_name: GitHubActionsBot
        # The directory where your repository is located. You should use actions/checkout first to set it up
        #cwd: # optional, default is .
        # Whether to use the force option on git add, in order to bypass eventual gitignores
        #force: # optional, default is false
        # The message for the commit
        message: "Updating primer.pdf"
        # Name of the branch to use, if different from the one that triggered the workflow
        #ref: docs
        # Arguments for the git rm command
        #remove: # optional, default is 
        # The name of the tag to add to the new commit
        tag: docs-bot
